import org.jetbrains.dokka.gradle.DokkaTask

/*
 * Copyright (C) 2019 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

plugins {
    id("com.android.application") version '8.7.3' apply false
    id("com.android.library") version '8.7.3' apply true
    id("org.jetbrains.kotlin.android") version "2.1.21" apply true
    id("org.jetbrains.dokka") version "2.0.0" apply true
}

apply from: new File("manifest.gradle")

android {
    compileSdk = 35
    namespace = "androidx"
}

def loadGithubProperties() {
    def props = new Properties()
    def propsFile = rootProject.file("github.properties")
    if (propsFile.exists()) {
        propsFile.withInputStream { props.load(it) }
    }
    return props
}


ext {
    githubProps = loadGithubProperties()
    ghUsernameResolved = System.getenv('GH_USERNAME') ?:
            project.findProperty('ghUsername') ?:
                    (githubProps.getProperty('ghUsername'))
    ghAccessTokenResolved = System.getenv('GH_ACCESS_TOKEN') ?:
            project.findProperty('ghAccessToken') ?:
                    (githubProps.getProperty('ghAccessToken'))
}

allprojects {
    repositories {
        google()
        mavenCentral()

        maven {
            url = uri("https://maven.pkg.github.com/tribalfs/sesl-androidx")
            credentials {
                username = rootProject.ext.ghUsernameResolved
                password = rootProject.ext.ghAccessTokenResolved
            }
        }
        maven {
            url = uri("https://maven.pkg.github.com/tribalfs/sesl-material-components-android")
            credentials {
                username = rootProject.ext.ghUsernameResolved
                password = rootProject.ext.ghAccessTokenResolved
            }
        }
        maven {
            url = uri("https://maven.pkg.github.com/tribalfs/SeslStub")
            credentials {
                username = rootProject.ext.ghUsernameResolved
                password = rootProject.ext.ghAccessTokenResolved
            }
        }
        maven { url = uri("https://jitpack.io") }
        maven { url = uri("https://plugins.gradle.org/m2/") }
        mavenLocal()
    }
    tasks.withType(Javadoc).tap {
        configureEach {
            options.addStringOption('Xdoclint:none', '-quiet')
            options.addStringOption('encoding', 'UTF-8')
            options.addStringOption('charSet', 'UTF-8')
        }
    }
}

subprojects {
    if (!name.endsWith("-lint")) {
        apply plugin: "kotlin-android"
        apply plugin: "org.jetbrains.dokka"

        tasks.withType(DokkaTask).configureEach { dokkaTask ->
            dokkaTask.dokkaSourceSets.configureEach { sourceSet ->
                def localSrcDir = file("src/main/java")
                if (localSrcDir.exists()) {
                    sourceSet.sourceLink {
                        localDirectory.set(localSrcDir)
                        def moduleDir = "${projectDir.parentFile.name}/${project.name}"
                        remoteUrl.set("https://github.com/tribalfs/sesl-androidx/tree/sesl-androidx-main/${moduleDir}/src/main/java")
                        remoteLineSuffix.set("#L")
                    }
                }
            }
            suppressInheritedMembers.set(true)
            suppressObviousFunctions.set(true)
        }
    }
}

subprojects {
    project.plugins.whenPluginAdded { plugin ->
        def isAndroidLibrary = "com.android.build.gradle.LibraryPlugin" == plugin.class.name
        def isAndroidApp = "com.android.build.gradle.AppPlugin" == plugin.class.name
        def isAndroidTest = "com.android.build.gradle.TestPlugin" == plugin.class.name

        if (isAndroidLibrary || isAndroidApp || isAndroidTest) {
            project.android {
                def versionInfoKey = "androidx." + project.projectDir.getName()
                def version_info = rootProject.ext.versions_metadata[versionInfoKey]

                if (compileSdkPreview == null) {
                    compileSdk = version_info[4]
                }

                defaultConfig.minSdk = version_info[3]
                defaultConfig.targetSdk = version_info[4]

                if (isAndroidLibrary) {
                    defaultConfig.versionName = "${version_info[0]}+${version_info[1]}+${version_info[2]}"
                    println "set versionName=${defaultConfig.versionName}"

                    android {
                        lint {
                            baseline = file("lint-baseline.xml")
                        }
                    }

                    publishing {
                        singleVariant("release"){
                            withSourcesJar()
                            withJavadocJar()
                        }
                    }


                    afterEvaluate {
                        def JAVA_RESOURCES_TEMP_DIR = "$buildDir/javaResources"
                        def versionFileName = namespace + '_' + project.projectDir.getName() + '.version'
                        task writeVersionFile() {
                            def versionFileDir = JAVA_RESOURCES_TEMP_DIR + '/META-INF'
                            new File(versionFileDir).mkdirs()
                            new File(versionFileDir + '/' + versionFileName).text = defaultConfig.versionName + "\n"
                        }
                        println "writeVersionFile $defaultConfig.versionName >> $versionFileName"

                        libraryVariants.all {
                            it.processJavaResourcesProvider.get().dependsOn(writeVersionFile)
                        }

                        project.android.sourceSets.main.resources.srcDir JAVA_RESOURCES_TEMP_DIR

                        task updateVersionBadge() {
                            def readmeFile = file("${rootProject.projectDir}/README.md")
                            def readmeContent = new String(readmeFile.bytes)

                            def escapedGroupAndName = "${projectDir.parentFile.name}:${projectDir.name}"
                                    .replaceAll('\\.', '\\\\.').replaceAll('-', '--')
                            def badgeUrl = "https://img.shields.io/badge/sesl.androidx.$escapedGroupAndName-${version_info[0].replaceAll('-', '--')}%2B${version_info[1].replaceAll('-', '--')}%2B${version_info[2]}-blue?logo=GitHub"
                            def pattern = ~/https:\/\/img\.shields\.io\/badge\/sesl\.androidx\.$escapedGroupAndName-\d+.*blue\?logo=GitHub/

                            readmeContent = readmeContent.replaceFirst(pattern, badgeUrl)
                            new File(readmeFile.path).text = readmeContent
                        }

                    }

                }
            }
        }
        if (isAndroidLibrary) {

            project.afterEvaluate {
                publishing {
                    publications {
                        gpr(MavenPublication) {
                            version = android.defaultConfig.versionName
                            group = "sesl.androidx." + projectDir.parentFile.name
                            afterEvaluate {
                                from components.release
                            }

                        }
                    }

                    repositories {
                        maven {
                            name = "GitHubPackages"
                            /** Configure path of your package repository on Github
                             *  Replace GH_USERID with your/organisation Github userID and REPOSITORY with the repository name on GitHub
                             */
                            url = uri("https://maven.pkg.github.com/tribalfs/sesl-androidx")

                            credentials {
                                username = rootProject.ext.ghUsernameResolved
                                password = rootProject.ext.ghAccessTokenResolved
                            }
                        }
                    }
                }
            }
        }
    }
}