pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        mavenLocal()
        maven { url = uri("https://jitpack.io")}
        maven { url = uri("https://plugins.gradle.org/m2/")}
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = "sesl.androidx"

include(":core", ":core-ktx")
include(":customview")
include(":coordinatorlayout")
include(":drawerlayout")
include(":appcompat",":appcompat-lint" )
include(":recyclerview")
include(":preference")
include(":fragment",":fragment-lint" )
include(":viewpager2")
include(":swiperefreshlayout")
include(":viewpager")
include(":slidingpanelayout")
include(":indexscroll")
include(":picker-basic", ":picker-color", ":picker-app")
include(":apppickerview")

project(":core").projectDir = file("core/core")
project(":core-ktx").projectDir = file("core/core-ktx")
project(":customview").projectDir = file("customview/customview")
project(":coordinatorlayout").projectDir = file("coordinatorlayout/coordinatorlayout")
project(":drawerlayout").projectDir = file("drawerlayout/drawerlayout")
project(":appcompat").projectDir = file("appcompat/appcompat")
project(":appcompat-lint").projectDir = file("appcompat/appcompat-lint")
project(":recyclerview").projectDir = file("recyclerview/recyclerview")
project(":preference").projectDir = file("preference/preference")
project(":fragment").projectDir = file("fragment/fragment")
project(":fragment-lint").projectDir = file("fragment/fragment-lint")
project(":viewpager2").projectDir = file("viewpager2/viewpager2")
project(":swiperefreshlayout").projectDir = file("swiperefreshlayout/swiperefreshlayout")
project(":viewpager").projectDir = file("viewpager/viewpager")
project(":slidingpanelayout").projectDir = file("slidingpanelayout/slidingpanelayout")
project(":indexscroll").projectDir = file("indexscroll/indexscroll")
project(":picker-basic").projectDir = file("picker/picker-basic")
project(":picker-color").projectDir = file("picker/picker-color")
project(":picker-app").projectDir = file("picker/picker-app")
project(":apppickerview").projectDir = file("apppickerview/apppickerview")