[versions]
# -----------------------------------------------------------------------------
# All of the following should be updated in sync.
# -----------------------------------------------------------------------------
activity = "1.9.3"
androidGradlePlugin = "9.3.2"
androidLint = "32.3.2"
androidxTestRunner = "1.6.2"
androidxTestRules = "1.6.1"
androidxTestMonitor = "1.7.2"
androidxTestCore = "1.6.1"
androidxTestExtJunit = "1.2.1"
annotation = "1.10.0"
annotationExperimental = "1.6.0"
appcompatResources = "1.8.0"
collection = "1.6.0"
compose = "1.8.2"
concurrentFutures = "1.3.0"
coreViewtree = "1.0.0"
cursoradapter = "1.0.0"
customviewPoolingcontainer = "1.0.0"
dokka = "2.2.0"
dokkaGradlePlugin = "2.2.0"
emoji2 = "1.3.0"
emoji2ViewsHelper = "1.2.0"
espresso = "3.6.1"
fragment = "1.9.0"
interpolator = "1.0.0"
kotlin = "2.4.10"
kotlinGradlePlugin = "2.1.20"
lifecycle = "2.11.0"
loader = "1.0.0"
profileinstaller = "1.4.0"
resourceinspectionAnnotation = "1.0.1"
savedstate = "1.2.1"
shimmer = "0.5.0"
transition = "1.4.1"
versionedparcelable = "1.2.1"
window = "1.2.0"

[libraries]
androidLint = { module = "com.android.tools.lint:lint", version.ref = "androidLint" }
androidLintApi = { module = "com.android.tools.lint:lint-api", version.ref = "androidLint" }
androidLintChecks = { module = "com.android.tools.lint:lint-checks", version.ref = "androidLint" }
androidLintTests = { module = "com.android.tools.lint:lint-tests", version.ref = "androidLint" }
androidx-activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-annotation-experimental = { module = "androidx.annotation:annotation-experimental", version.ref = "annotationExperimental" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompatResources" }
androidx-collection = { module = "androidx.collection:collection", version.ref = "collection" }
androidx-collection-ktx = { module = "androidx.collection:collection-ktx", version.ref = "collection" }
androidx-concurrent-futures = { module = "androidx.concurrent:concurrent-futures", version.ref = "concurrentFutures" }
androidx-core-viewtree = { module = "androidx.core:core-viewtree", version.ref = "coreViewtree" }
androidx-cursoradapter = { module = "androidx.cursoradapter:cursoradapter", version.ref = "cursoradapter" }
androidx-customview-poolingcontainer = { module = "androidx.customview:customview-poolingcontainer", version.ref = "customviewPoolingcontainer" }
androidx-dynamicanimation = { module = "androidx.dynamicanimation:dynamicanimation", version = "1.1.0" }
androidx-emoji2 = { module = "androidx.emoji2:emoji2", version.ref = "emoji2" }
androidx-emoji2-views-helper = { module = "androidx.emoji2:emoji2-views-helper", version.ref = "emoji2ViewsHelper" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-interpolator = { module = "androidx.interpolator:interpolator", version.ref = "interpolator" }
androidx-lifecycle-livedata-core = { module = "androidx.lifecycle:lifecycle-livedata-core", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycle" }
androidx-loader = { module = "androidx.loader:loader", version.ref = "loader" }
androidx-profileinstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileinstaller" }
androidx-resourceinspection-annotation = { module = "androidx.resourceinspection:resourceinspection-annotation", version.ref = "resourceinspectionAnnotation" }
androidx-savedstate = { module = "androidx.savedstate:savedstate", version.ref = "savedstate" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "compose" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-transition = { module = "androidx.transition:transition", version.ref = "transition" }
androidx-tracing = { group = "androidx.tracing", name = "tracing", version = "2.0.1" }
androidx-versionedparcelable = { module = "androidx.versionedparcelable:versionedparcelable", version.ref = "versionedparcelable" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.0.1"}
dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokkaGradlePlugin" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
agp = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
androidKapt = { module = "com.android.legacy-kapt:com.android.legacy-kapt.gradle.plugin", version.ref = "androidGradlePlugin" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.1" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinStdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib" }

sesl-androidx-appcompat = { module = "sesl.androidx.appcompat:appcompat", version = "1.7.1+1.0.21-sesl8+rev8" }
sesl-androidx-coordinatorlayout = { module = "sesl.androidx.coordinatorlayout:coordinatorlayout", version = "1.3.0+1.0.0-sesl8+rev0" }
sesl-androidx-core = { module = "sesl.androidx.core:core", version = "1.18.0+1.0.7-sesl8+rev0" }
sesl-androidx-coreKtx = { module = "sesl.androidx.core:core-ktx", version = "1.17.0+1.0.0-sesl8+rev0" }
sesl-androidx-customview = { module = "sesl.androidx.customview:customview", version = "1.2.0-rc01+1.0.0-sesl8+rev0" }
sesl-androidx-drawerlayout = { module = "sesl.androidx.drawerlayout:drawerlayout", version = "1.2.0+1.0.0-sesl8+rev0" }
sesl-androidx-fragment = { module = "sesl.androidx.fragment:fragment", version = "1.8.9+1.0.5-sesl8+rev1" }
sesl-androidx-recyclerview = { module = "sesl.androidx.recyclerview:recyclerview", version = "1.4.0+1.0.12-sesl8+rev3" }
sesl-androidx-viewpager = { module = "sesl.androidx.viewpager:viewpager", version = "1.1.0-beta01+1.0.0-sesl8+rev0" }
sesl-androidx-viewpager2 = { module = "sesl.androidx.viewpager2:viewpager2", version = "1.1.0+1.0.0-sesl8+rev0" }
sesl-material = { module = "sesl.com.google.android.material:material", version = "1.12.0+1.0.31-sesl8+rev0" }

shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
testCore = { module = "androidx.test:core", version.ref = "androidxTestCore" }
testExtJunit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
testMonitor = { module = "androidx.test:monitor", version.ref = "androidxTestMonitor" }
testRules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
testRunner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
truth = { module = "com.google.truth:truth", version = "1.0.1" }


[plugins]
androidLibrary = { id = "com.android.library" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka"  }
legacyKapt = { id = "com.android.legacy-kapt", version.ref = "androidGradlePlugin" }
kotlinParcelize = { id = "kotlin-parcelize" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
mavenPublish = { id = "maven-publish" }

[bundles]